### ISSUE TITLE
brouter web - routing not working

### ISSUE THREAD

**Issue by tectoni** [nrenner/brouter-web#679]
At current, routing between trackpoints is not working during creation of paths. (machine macos 11.6.1, Safari 15.6.1 and Firefox). This applies to different instances of brouter (brouter.de, brouter.damsy.net, but NOT on bikerouter.de, which is working fine.)
No paths are drawn, instead only running ants lines between waypoints are drawn. 
Also are 404 Not Found and 502 Bad Gateway Errors frequently occuring.

**Comment by nrenner** [comment]
Thanks for reporting.

I restarted the routeserver process, https://brouter.de/brouter-web should be working again.

**Comment by AdelheidNaps** [comment]
no - nix working (22.11.2022 20:34h)
Es ist more and more nervig zu arbeiten mit Brouter (mühsam lange Route geplant - bums der ganze Mist hängt. und man möchte treten gegen Computer - Mist! den habe ich ja selbst bezahlt 

Grüße
Adelheid

**Comment by tectoni** [comment]
Thanks for the reply. 

However, no changes. The issue is still persists.

--
Dr. Peter Appel
Institut für Geowissenschaften
CAU Kiel
Ludewig-Meyn-Str. 10
24118 Kiel
Tel. +494318802900
Mobil +4915115273436
***@***.***

**Comment by polyscias** [comment]
Just tried https://brouter.de/brouter-web, everything is working fine for me on Firefox.

**Comment by tectoni** [comment]
All ok now.  Routing is working and up to now no error messages appear.
Thanks, Peter
--
Dr. Peter Appel
Institut für Geowissenschaften
CAU Kiel
Ludewig-Meyn-Str. 10
24118 Kiel
Tel. +494318802900
Mobil +4915115273436
***@***.***

**Comment by nrenner** [comment]
I have seen some sporadic OutOfMemoryErrors in the logs and it got stuck again earlier, so I restarted it again. Will keep an eye on it.
